### ISSUE TITLE
Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by nishanth919** [technikhil314/angular-components#33]
**Unexpected value 'DaterangepickerModule in /xxx/node_modules/angular-2-daterangepicker/index.js' imported by the module 'AgreeGatewayV1DashboardverModule in myprj/my.module.ts'. Please add a @NgModule annotation.**

Hi Nikhil 

I have imported and started utilizing you angular-2-daterangepicker. when i'm running in a developer env this is working fine. But when i'm trying to make a package to run in prod env, its through below error. Can you please help me out in this.

`Unexpected value 'DaterangepickerModule in /xxx/node_modules/angular-2-daterangepicker/index.js' imported by the module 'myModule in myprj/my.module.ts'. Please add a @NgModule annotation.`

i am using  "@angular/core": "4.4.6".

I read below URL, does this applicable. If so how can i upgrade andgular/core version of angular-2-daterangepicker.
`

> https://github.com/angular/angular/issues/15763

`

**Comment by nikhil-001mehta** [comment]
sure @nishanth919 
I will look into it. Will update you soon.

**Comment by nikhil-001mehta** [comment]
@nishanth919 Are you using shrinkwrap or fixed version for @angular/core

**Comment by nishanth919** [comment]
@nikhil-001mehta i am not using shrinkwrap. mine is a Maven project so using Maven packager command.

**Comment by rafiq-ahmed-1** [comment]
Facing same issue. 

> "@angular/core": "^4.3.6"

DatePicker Version:
> "angular-2-daterangepicker": "^1.1.44",

**Comment by nikhil-001mehta** [comment]
Yup I will look into it.

**Comment by myahi** [comment]
@nikhil-001mehta i'm facing the same issue, do you have any updates ?
thank's

**Comment by David-Mawer** [comment]
@technikhil314 - OK, so I started using the component, and I find the same issue under the following conditions: -
Angular 6
with the following compiler options:
buildOptimizer: true,
aot: true

I noticed that as soon as I set these 2 options to false, then the build works.

So it's something to do with aot (which is where strict type definitions are enforced at compile time).

**Comment by technikhil314** [comment]
@David-Mawer Oh ok. Thanks for this insight. I will dig more into it and will fix it.

**Comment by technikhil314** [comment]
@nishanth919 @David-Mawer @rafiq-ahmed-1 @myahi For this I need to change overall architecture of my module. Currently i am relying on system loader for my development. But it seems I need to use angular/cli. Please expect some delay in this issue to get resolved. Sorry for this delay. And thanks for all your support.

**Comment by sirespin** [comment]
I have the same problem and can't deploy :(

`[ts]
No declaration file was found for the module 'angular-2-daterangepicker'. '*/node_modules/angular-2-daterangepicker/index.js' has an implicit "any" type.
   Try npm install @ types / angular-2-daterangepicker if it exists or add a new declaration (.d.ts) file containing declare module 'angular-2-daterangepicker'; [7016]`

**Comment by Abadii** [comment]
Same issue, since it's an open topic for a long time, I uninstalled..

**Comment by vatsenko** [comment]
Have same issue

**Comment by gomteshhatgine** [comment]
@technikhil314 
yes something wrong with **aot** (which is where strict type definitions are enforced at compile time).
because without aot build was sucessfull
please comment once you fix this issue

**Comment by natibs** [comment]
Having same issue.

**Comment by G-007** [comment]
ERROR in : Unexpected value 'DaterangepickerModule in C:/xxx/node_modules/angular-2-daterangepicker/index.js' imported by the module 'AppModule in C:/xxx/src/app/app.module.ts'. Please add a @NgModule annotation.

Please help me to find out this issue.

**Comment by G-007** [comment]
I have used npm angular-2-daterangepicke and follow steps that are given here (https://www.npmjs.com/package/angular-2-daterangepicker). This date range picker is working fine in my local machine but while making build for the production it gives some error as given below. ERROR in: Unexpected value 'DaterangepickerModule in C:/xxx/node_modules/angular-2-daterangepicker/index.js' imported by the module 'AppModule in C:/xxx/src/app/app.module.ts'. Please add a @NgModule annotation. In app.module.ts I have code like this.

import { DaterangepickerModule } from 'angular-2-daterangepicker';
@NgModule({
  declarations: [],
  imports: [
    DaterangepickerModule
  ]
})
export class AppModule { }
If there is someone who can solve this problem then please help me to find out the solution to this problem. I have got some temporary solution on GitHub for making a build, by searching for the solution of the same problem i.e. (ng build --prod --aot=false --build-optimizer=false) but I think it is not the right way to create a build.

**Comment by kernyden** [comment]
same issue

**Comment by GMithapara-Fintech** [comment]
same issue please help me if you found any solution

**Comment by hustakin** [comment]
same issue, still no update on this please???

**Comment by technikhil314** [comment]
hey @hustakin  @GMithapara-Fintech @kernyden  @G-007 @natibs @vatsenko @Abadii @sirespin @David-Mawer @myahi @nishanth919 If you are on angular v6 or later please use this package. https://www.npmjs.com/package/angular-datetimerangepicker

**Comment by technikhil314** [comment]
This is fixed in v2.1.1

https://www.npmjs.com/package/angular-datetimerangepicker
