### ISSUE TITLE
New feature suggestion: disable specific dates 

### ISSUE THREAD

**Issue by sunloverz** [technikhil314/angular-components#36]
I think many users use this daterangepicker for reservation, booking something, so it would be nice to add a feature for disabling specific dates.

**Comment by technikhil314** [comment]
@sunloverz And do you suggest we do that. by passing in a whole array of dates which you want to disable or just disbledWeekEnds will it suffice your needs?

**Comment by sunloverz** [comment]
I think its better to disable dates by passing an array of dates. Something like disableDates: [{year: 2018, month: 10, day: 1}, {year: 2018: month: 10, day: 2}]
Or even better also add a feature to disable date ranges.

**Comment by technikhil314** [comment]
Done in v2.3.2
