### ISSUE TITLE
Not Working with Angular 6, Also bug (cannot select date range more than couple months)

### ISSUE THREAD

**Issue by playnox** [technikhil314/angular-components#39]
1. This datepicker doesn't work with latest Angular release (please fix the issue reported in #38)
    Getting this error:
`DaterangepickerComponent.html:28 ERROR TypeError: this.fromDate.format is not a function
at DaterangepickerComponent.push../node_modules/angular-2-daterangepicker/daterangepicker-component.js.DaterangepickerComponent.formatFromDate (daterangepicker-component.js:353)
at Object.eval [as handleEvent] (DaterangepickerComponent.html:31)`

When **startDate** and **endDate** is not set or set to **NULL**
`
this.daterangepickerOptions = {
            startDate: null,
            endDate: null,
     ...
`

**Comment by technikhil314** [comment]
@playnox https://www.npmjs.com/package/angular-datetimerangepicker

**Comment by technikhil314** [comment]
This is fixed in v2.1.1

https://www.npmjs.com/package/angular-datetimerangepicker
