### ISSUE TITLE
Unable to contribute

### ISSUE THREAD

**Issue by aliarshad9691** [technikhil314/angular-components#41]
The steps provided to setup development points to this [gist](https://gist.github.com/nikhil-001mehta/7a43a4da53ed9809fd6682a340ede618)
The gist does not exist and return 404.

**Comment by technikhil314** [comment]
@aliarshad9691 I am extremely sorry for the inconvience. Here it link to the gist. https://gist.github.com/technikhil314/85e7d8a38ab459b3aa2117fe4d713e5b

**Comment by technikhil314** [comment]
@aliarshad9691 I hope it solves your problem

**Comment by technikhil314** [comment]
This is made more easy in v2.1.1

https://www.npmjs.com/package/angular-datetimerangepicker
