### ISSUE TITLE
Error import module

### ISSUE THREAD

**Issue by rocoradi** [technikhil314/angular-components#44]
Erro on app.module: 
`Could not find a declaration file for module 'angular-2-daterangepicker'. '/home/desenvolvimento017/repositorio/ecm-admin-frontend/ecm-admin-frontend/node_modules/angular-2-daterangepicker/index.js' implicitly has an 'any' type.
  Try `npm install @types/angular-2-daterangepicker` if it exists or add a new declaration (.d.ts) file containing `declare module 'angular-2-daterangepicker';`ts(7016)`

![image](https://user-images.githubusercontent.com/20579384/54616292-35a5d900-4a3e-11e9-9309-32e0306575d6.png)

I can not use...

**Comment by technikhil314** [comment]
This is fixed in v2.1.1

https://www.npmjs.com/package/angular-datetimerangepicker
