### ISSUE TITLE
Getting error in angular-2-daterangepicke module while making build in angular 2

### ISSUE THREAD

**Issue by anand171** [technikhil314/angular-components#45]
Hello Everyone,
I have used npm angular-2-daterangepicke and follow steps that are given here (https://www.npmjs.com/package/angular-2-daterangepicker). This date range picker is working fine in my local machine but while making build for the production it gives some error as given below.

ERROR in: Unexpected value 'DaterangepickerModule in C:/xxx/node_modules/angular-2-daterangepicker/index.js' imported by the module 'AppModule in C:/xxx/src/app/app.module.ts'. Please add a @NgModule annotation.

In app.module.ts I have code like this.

import { DaterangepickerModule } from 'angular-2-daterangepicker';
@NgModule({
  declarations: [],
  imports: [
    DaterangepickerModule
  ]
})
export class AppModule { }

If there is someone who can solve this problem then please help me to find out the solution to this problem.

I have got some temporary solution on GitHub for making a build, by searching for the solution of the same problem i.e. (ng build --prod --aot=false --build-optimizer=false) but I think it is not the right way to create a build.

**Comment by technikhil314** [comment]
This is fixed in v2.1.1

https://www.npmjs.com/package/angular-datetimerangepicker
