### ISSUE TITLE
First day of week

### ISSUE THREAD

**Issue by danieldesko** [technikhil314/angular-components#47]
We are using this component on our Angular app, so we need first day of week to be Monday, we can't find solution to make this.

Is there any property in Options to set the first day in Calendar to be Monday, or how can we solve this? We didn't find anything of that.

If doesn't exist, I'm suggesting you to implement this feature in next versions of this component, it is useful for user from the eastern parts of the Earth.

**Comment by technikhil314** [comment]
Yes will release it over this weekend. Thanks.

**Comment by technikhil314** [comment]
Hey @danieldesko Just realised I had made provision for it already. It was quick to add this options. And is available in v2.2.10

**Comment by danieldesko** [comment]
Thank you for fast response and updated version.

**Comment by technikhil314** [comment]
Added the support in v2.2.10. Closing.
