### ISSUE TITLE
add option to remove clear button

### ISSUE THREAD

**Issue by vithano** [technikhil314/angular-components#48]
im using your component in my project and it would be cool if there was an optiion to remove the clear button or the entire bottom row of buttons

**Comment by technikhil314** [comment]
@vithano hey may I know the exact use case? We may find a better solution if we discuss.

**Comment by vithano** [comment]
well currently i use it as a datepicker for a calendar, so i dont need the user to clear the value, it should always have a default value as the current date, at the moment i just use css and remove the entire bottom row, but it feels hacky
![image](https://user-images.githubusercontent.com/11342649/100559446-5d44df80-32bb-11eb-9cc4-d639a4e2a7cb.png)

**Comment by vithano** [comment]
i dont wanna overload this request but it would also be nice to give me the option to make the input readonly so the user can only change the dates using the date picker and not manually typing

**Comment by technikhil314** [comment]
ok makes sense I will add these two options

**Comment by technikhil314** [comment]
This is now supported in v2.3.0 

Check hideControls and readOnly option in documentation

**Comment by vithano** [comment]
works great, thanks for the work
