### ISSUE TITLE
bug report: cant import component

### ISSUE THREAD

**Issue by vithano** [technikhil314/angular-components#49]
hi im trying to import the daterangepicker component and im getting this error:
![image](https://user-images.githubusercontent.com/11342649/100652597-d2fa8b00-334f-11eb-9ce8-9e4cff7b9fb7.png)

im importing like this:
import { DaterangepickerComponent } from 'angular-datetimerangepicker/daterangepicker/daterangepicker.component';
and i do have the module in my app.module.ts

**Comment by technikhil314** [comment]
Hey you should not import component. But you should import daterangepicker module instead.

Check this example here
https://stackblitz.com/edit/angular-datetimerangepicker-demo-without-bootstrap

Also check the https://technikhil314.netlify.app/docs/daterangepicker/how-to-use

You just need to add two lines to your `app.module.ts` and then start using the component

**Comment by vithano** [comment]
here is what im trying to do , when changing the date from a different source, in my case buttons that move the selected time frame to next week/previous week and today i want this to be reflected on the date picker(you can see the picture in the previous request i made)
im referencing your component as #datepicker 
![image](https://user-images.githubusercontent.com/11342649/100749753-c3318400-33ed-11eb-82a9-fa044a4cefcc.png)
 then im changing the date on it dynamically like this, i cant use the actual component because of that error and i m forced to use "any" instead

![image](https://user-images.githubusercontent.com/11342649/100749414-4dc5b380-33ed-11eb-85cb-9080f47db98d.png)

**Comment by technikhil314** [comment]
Probably you are using it in wrong way. You simply need to change the options object in viewDateChange function. And it should work. Cause daterangepicker component handles ngOnChanges event already. Check the stackblitz example. See how the options change dynamically in that example. What you are doing is hacky way.

**Comment by vithano** [comment]
things ive tried:
![image](https://user-images.githubusercontent.com/11342649/100768935-1b738080-3404-11eb-9bf6-7421d8712df5.png)
this didn't work, had no effect on values
![image](https://user-images.githubusercontent.com/11342649/100769068-3d6d0300-3404-11eb-89a8-614e19d3d4c1.png)
this worked only if i added setRange, without it the changes werent propagating to the value of the input
with:
![image](https://user-images.githubusercontent.com/11342649/100769301-845af880-3404-11eb-9c1c-c8acdd3816f4.png)
without:
![image](https://user-images.githubusercontent.com/11342649/100769466-be2bff00-3404-11eb-8cad-9fdf3ef5d4fb.png)

**Comment by technikhil314** [comment]
Ok got your use case now. I will release new version for this.

**Comment by technikhil314** [comment]
Please use v2.3.1

You simply need to pass new options object from your `viewDateChange` function. something like

```
viewDateChange(date: Date) {
    this.daterangepickerOptions = {
        ...this.daterangepickerOptions,
        startDate: Dayjs(date).startOf('day'),
        endDate: Dayjs(date).add(7, 'day').endOf('day')
    }
}
```

This should work now need of calling `setRange` etc.

**Comment by vithano** [comment]
works well now ,thanks for the quick fixes
