### ISSUE TITLE
Few suggestions for better experience

### ISSUE THREAD

**Issue by danieldesko** [technikhil314/angular-components#50]
Hi, 

I have few suggestions for better experience and usability of this component.

If it's possible to add feature two calendars to be linked (left calendar to show eg. December and the right calendar to show January) and the user to be able to select date range as he wants from December to January or just in December or in January etc. This option to be controlled by flag in date range picker options (eg: linkedCalendars: true/false)

Also for inputs in date range picker can you add flag in options developer to check if he wants inputs to be readOnly or end-user can add custom dates (some users prefer to add custom dates in inputs and then they will be selected in calendars)

Thanks in advance.
Daniel

**Comment by technikhil314** [comment]
Yeah the first suggestion is already in WIP. But for second one it adds unwanted compexicity of checking date format inputted by user. I can understand it from user experience point of view. Do you have any approach in mind on how to handle wrong date formats inputed by user?

**Comment by danieldesko** [comment]
Maybe it would be better user can't enter wrong date, input fields to be pre-formatted for entering dates in format that is already entered in options. If is defined format to be DD/MM/YYYY then input fields will accept only that format and automatically as you are entering it will be formatted.

Maybe this can help inputs not to be text type, but date. 
<input type='date'> 

This type of inputs automatically adds an icon which is clickable and opens date picker, so that icon can be hidden.

Or maybe input can stay as text type but input as you type can be formatted like this image bellow.
[https://www.aspsnippets.com/Handlers/DownloadFile.ashx?File=875cb04e-ac6b-4eef-ac08-6a5a8aa17ae6.gif](url)

**Comment by technikhil314** [comment]
ah got it. Will be too much for this package to handle. I am afraid the component will explode in size. My target is to keep it in limit of 10kb mingzipped. This package has already touched 12kb mark. But never mind I will see what I can do and come back here for any help. Thanks.
