### ISSUE TITLE
"Auto Apply" not working

### ISSUE THREAD

**Issue by BrunoWB** [technikhil314/angular-components#59]
Bug:
The "Auto Apply" option is not working.

Expected Behaviour:
I couldn't find a description to what it is supposed to do, but I'm assuming it is used in combo with "hide controls" so we can get the output on the day selection action.

Reproduce:
- Angular 12.0.4
- Datetimerangepicker: 2.4.3
- Chrome Version 91.0.4472.114
(As for now jul/2021 the demo is also not working https://angular-datetimerangepicker.surge.sh/)

__ footnote:
Very useful module, thank you sir :)

**Comment by technikhil314** [comment]
@BrunoWB 
If you have time picker enabled its not easy to decide on when to auto apply. 
So it get automatically disabled. Try disabling timepicker and auto apply will work fine.

**Comment by BrunoWB** [comment]
This makes for a very inconsistent behaviour, when you say "not easy to decide on when to auto apply" you mean functionality-wise or technical/code-wise?
If you think this should stay as is, I'd recommend adding a mutual exclusion contraint on the demo, so ppl will know that using the timepicker will disable auto-apply. :) 

(getting a bit ahead of your answer, if you meant functionality-wise) Ideas for expected UX behaviour:
I'd think having the (rangeSelected) for when user press 1)apply | (if on flyout mode) 2)press enter or 3)exits the "flyout" calendar. this would also be legacy-friendly ppl wouldn't have issues updating the component
add (rangeChanged) outputs an event any time calendar suffered a change from user input, in the date or in time, I think this is going to be most useful for devs, we can handle changes as we see fit
