### ISSUE TITLE
The next/previous button trigger submit form

### ISSUE THREAD

**Issue by lukancosta** [technikhil314/angular-components#60]
**Describe the bug**

When the "app-datetimepicker" is added inside a form e.g., 

`<form (ngSubmit)="formCreate(formValue)" #formValue="ngForm">

<app-datetimepicker></app-datetimepicker>
<button type="submit">Submit</button>

</form>`

, the calendar's next/previous button triggers the submit form button - when using a template-driven approach.

I think the problem can be solved if the next/previous button has the attribute "type="button". By default it gets the "submit" type when a type is not informed.

**Comment by technikhil314** [comment]
Hey thanks for reporting this. I have fixed it in v2.4.4

**Comment by technikhil314** [comment]
Fixed in v2.4.4
