### ISSUE TITLE
Issue while installing with Angular 11.

### ISSUE THREAD

**Issue by suriyaJaay** [technikhil314/angular-components#64]
Hi Am getting below error, while installing..
package.json
------------

"dependencies": {
    "@angular/animations": "~11.2.8",
    "@angular/cdk": "~11.2.13",
    "@angular/common": "~11.2.8",
    "@angular/compiler": "~11.2.8",
    "@angular/core": "~11.2.8",
    "@angular/forms": "~11.2.8",
    "@angular/material": "~11.2.13",
    "@angular/platform-browser": "~11.2.8",
    "@angular/platform-browser-dynamic": "~11.2.8",
    "@angular/router": "~11.2.8",
}

![image](https://user-images.githubusercontent.com/19813670/142392271-aef5b17d-0091-4f55-806f-7cd4afa61854.png)

Could you pls help me on this?

**Comment by technikhil314** [comment]
@suriyaJaay  can you try with --force. I just checked angular/common@6.0.0-rc-0 is still available on npm registry. let me know if it does not work I will change the peer dependancy version and publish new version.

**Comment by radiumrasheed** [comment]
> @suriyaJaay can you try with --force. I just checked angular/common@6.0.0-rc-0 is still available on npm registry. let me know if it does not work I will change the peer dependancy version and publish new version.

I think it's best to change the peer deps instead of using force, to ease ci-cd

**Comment by technikhil314** [comment]
> > @suriyaJaay can you try with --force. I just checked angular/common@6.0.0-rc-0 is still available on npm registry. let me know if it does not work I will change the peer dependancy version and publish new version.
> 
> I think it's best to change the peer deps instead of using force, to ease ci-cd

Yup makes sense. I will release new patch version with the changes.
